### ISSUE TITLE
CSS not getting included

### ISSUE THREAD

**Issue by brasilikum** [embermap/ember-cli-tailwind#31] opened 2018-05-24 21:18 UTC
Hey,

first off I want to thank you, this is a great project.

I tried to include it in our project (wich is not open source) and it did not work. Not even the styleguide is styled, so the styles do not seem to get included. I changed nothing in the config, only included the plugin with compile target 'app'.

How can I debug this? I already looked in the assets/vendor.css and there are not tailwind classes at all.

**Comment by samselikoff** [comment] 2018-05-24 21:35
You're welcome! Hope we can get it working for you.

What versions of everything are you on? Have you tried in a brand new app, just to see if things are working there? Sometimes producing a simplified reproduction is the best way to diagnose these types of issues.

**Comment by brasilikum** [comment] 2018-05-24 21:39
I looked further into it and most probably the reason is that we use less in our project as well. We want to replace it eventually but for the time being both would have to co-exist. 
It would also be ok to have the compliled file be included as an additional file.
Maybe it should not be the concern of this library. It would just be nice for incremental adoption.

I am using the latest version.

**Comment by samselikoff** [comment] 2018-05-30 18:11
@brasilikum the location should be `app/styles/tailwind.css`, any chance you could spot that in your build?

**Comment by brasilikum** [comment] 2018-06-01 14:32
@samselikoff The folder is there, but the compiled output is only included in the vendor.css, right?

It seems the styles are getting included the right way now (reinstalled and reconfigured).

However the styleguide is still not correctly styled. It seems to be an issue where in the styleguide everything gets prefixed with etw- in the stylesheet, but for example background color classes in the stylesheet do not have the prefix. If I add it manually it works

**Comment by brasilikum** [comment] 2018-06-01 14:38
pretty sure it is lines like this:

https://github.com/embermap/ember-cli-tailwind/blob/2e0be592e3c63b1931ff5f27df7919d608acfd08/app/templates/components/etw/module-style-example.hbs#L22

**Comment by samselikoff** [comment] 2018-06-03 15:30
The etw classes come from a separate static build of tailwind (configured with that prefix) and those are used to style the styleuide. They shouldn’t be affected by userland styles.

**Comment by ChrizzDF** [comment] 2018-06-09 18:11
Hey guys,

I have the same problem @brasilikum describes. I already updated to 0.5.1 but the problem remains. I wanted to change the separater from `:` to `_` because if I want to use classNameBindings e.g. `active:hover:bg-blue` it's creating problems.
I did this change in
```
./tailwind.js

  options: {
    prefix: '',
    important: false,
    separator: '_',
  },
```
I would expect `./app/styles/tailwind.css` to be automatically recompiled according to the new settings I made - no matter if in `./tailwind.js` or in `./tailwind/**` but that didn't happen. Even after executing `ember generate ember-cli-tailwind` and restarting the server wasn't helping.

Then I just removed `./app/styles/tailwind.css` because I wanted to see at which point it gets generated but seems like nothing is generating it.

Maybe it's a problem that I use `ember-cli-sass` (v.7.1.7) in my project?

Would be so nice if we could get it working! 🤩

**Comment by brasilikum** [comment] 2018-06-11 23:51
Thanks @samselikoff for following up on this. No, unfortunately it still does not seem to work.
When I run ember server, the plugin does not show up in the logs. If I change the js config of tailwind, it does show up as:
```
LessCompiler (1)                              | 1621ms
Rollup (3)                                    | 737ms (245 ms)
BuildTailwindPlugin (1)                       | 357ms
```
The problem is still that is does not show up under dist/ and does not get included, not even on the /tailwind page.

Anything else I can do to help with debugging?

**Comment by samselikoff** [comment] 2018-06-12 02:49
Since there are so many moving parts a minimal reproduction on github would enable me to clone it locally and debug it there. Would you be able to do that?

**Comment by samselikoff** [comment] 2018-06-12 19:32
@brasilikum I may have found the problem... can you paste in your `tailwind/modules.css` file? (It should have been generated when you installed the addon).

**Comment by brasilikum** [comment] 2018-06-12 20:39
/**
* This injects Tailwind's base styles, which is a combination of
* Normalize.css and some additional base styles.
*
* You can see the styles here:
* https://github.com/tailwindcss/tailwindcss/blob/master/css/preflight.css
*
* If using `postcss-import`, use this import instead:
*
* @import "tailwindcss/preflight";
*/
@tailwind preflight;

/**
* This injects any component classes registered by plugins.
*
* If using `postcss-import`, use this import instead:
*
* @import "tailwindcss/components";
*/
@tailwind components;

/**
* Here you would add any of your custom component classes; stuff that you'd
* want loaded *before* the utilities so that the utilities could still
* override them.
*
* Example:
*
* .btn { ... }
* .form-input { ... }
*
* Or if using a preprocessor or `postcss-import`:
*
* @import "components/buttons";
* @import "components/forms";
*/
@import "./components/*.css";

/**
* This injects all of Tailwind's utility classes, generated based on your
* config file.
*
* If using `postcss-import`, use this import instead:
*
* @import "tailwindcss/utilities";
*/
@tailwind utilities;

/**
* Here you would add any custom utilities you need that don't come out of the
* box with Tailwind.
*
* Example :
*
* .bg-pattern-graph-paper { ... }
* .skew-45 { ... }
*
* Or if using a preprocessor or `postcss-import`:
*
* @import "utilities/background-patterns";
* @import "utilities/skew-transforms";
*/
@import "./utilities/*.css";

**Comment by samselikoff** [comment] 2018-06-12 20:42
@brasilikum Yep, that's what I thought. When we upgraded Tailwind we botched the generated modules.css file – it mixes `@tailwind` directives with PostCSS `@import` statements.

Try copying + pasting this one:

```
/**
* This injects Tailwind's base styles, which is a combination of
* Normalize.css and some additional base styles.
*
* You can see the styles here:
* https://github.com/tailwindcss/tailwindcss/blob/master/css/preflight.css
*/
@import "tailwindcss/preflight";

/**
* This injects any component classes registered by plugins.
*/
@import "tailwindcss/components";

/**
* Here you would add any of your custom component classes; stuff that you'd
* want loaded *before* the utilities so that the utilities could still
* override them.
*/
@import "./components/*.css";

/**
* This injects all of Tailwind's utility classes, generated based on your
* config file.
*/
@import "tailwindcss/utilities";

/**
* Here you would add any custom utilities you need that don't come out of the
* box with Tailwind.
*/
@import "./utilities/*.css";
```

**Comment by samselikoff** [comment] 2018-06-13 00:32
Strange. If you publish a simplified example I should be able to figure it
out.

**Comment by yohanmishkin** [comment] 2018-06-25 01:13
[This](https://github.com/embermap/ember-cli-tailwind/issues/31#issuecomment-396726565) fixed things for me. Thanks, @samselikoff !

**Comment by samselikoff** [comment] 2018-08-13 17:55
@brasilikum Can you try

```less
@import (inline) 'tailwind.css';
```

in your `app.less` file and see if that works?

**Comment by brasilikum** [comment] 2018-08-14 14:33
@samselikoff thank you so much for following up on this! 
I cannot currently test this as I am on a backend project, but I will do the next time I get the chance.
I have to switch from directly including the externally compiled file back to your plugin, but that would most certainly help with flashes in the css

**Comment by samselikoff** [comment] 2018-08-17 17:26
Added install instructions to README https://github.com/embermap/ember-cli-tailwind/commit/aa8c4248d432c45f92df6800fc94c795473340f1

Closing for now but please ping if anyone's still having trouble here!

**Closed by samselikoff** 2018-08-17 17:26 UTC
Labels: Bug
